name: Maven Build

on:
  push:
    branches: [version4]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven Dependencies (~/.m2/repository)
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-:

    - name: Build with Maven
      run: mvn -B clean package

    - name: Deploy to Staging
      run: mvn -B deploy -DskipTests

    - name: Deploy OWLAPI OSGi Distribution
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./osgidistribution/target/mvn-repo
        keep_files: true
